package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

type kind int

const (
	kindPrimitive kind = iota
	kindSlice
	kindMap
	kindPointerPrimitive
	kindPointerStruct
	kindStruct
)

type field struct {
	name  string
	fType string
	kind  kind
}

type structData struct {
	name   string
	fields []field
}

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedCompiledGoFiles |
			packages.NeedSyntax,
		Dir: ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		slog.Error("Failed to load packages", "error", err)
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			for _, pkgErr := range pkg.Errors {
				slog.Warn("Package warning", "pkg", pkg.PkgPath, "error", pkgErr)
			}
			continue
		}

		processPackage(pkg)
	}
}

func processPackage(pkg *packages.Package) {

	var data []structData
	var dirPath string

	for _, file := range pkg.Syntax {
		fileToken := pkg.Fset.File(file.Pos())
		if fileToken == nil {
			continue
		}

		filename := fileToken.Name()
		if strings.HasSuffix(filename, "_test.go") || strings.HasSuffix(filename, ".gen.go") {
			continue
		}

		// first file fills directory name
		if dirPath == "" {
			dirPath = filepath.Dir(filename)
		}

		ast.Inspect(file, func(n ast.Node) bool {

			// skipping functions with all content
			if _, ok := n.(*ast.FuncDecl); ok {
				return false
			}

			// looking for GenDecl
			if genDecl, ok := n.(*ast.GenDecl); ok {
				// looking for TYPE decl. If other type, skip content
				if genDecl.Tok != token.TYPE {
					return false
				}

				newData := processGenDecl(genDecl)
				data = append(data, newData...)
			}

			return true
		})
	}

	if len(data) > 0 && dirPath != "" {
		if err := generateResetFile(dirPath, pkg.Name, data); err != nil {
			slog.Error("Failed to create file", "dir", dirPath, "error", err)
		}
	}
}

func processGenDecl(genDecl *ast.GenDecl) []structData {
	var data []structData

	isGroupComment := checkResetComment(genDecl.Doc)

	for _, spec := range genDecl.Specs {
		typeSpec, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			continue
		}

		isStructComment := checkResetComment(typeSpec.Doc)

		if isGroupComment || isStructComment {
			structData := structData{
				name:   typeSpec.Name.Name,
				fields: extractFields(structType),
			}

			data = append(data, structData)
		}
	}

	return data
}

func checkResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}

	return strings.HasPrefix(doc.Text(), "generate:reset")
}

func extractFields(structType *ast.StructType) []field {
	var fields []field

	if structType.Fields == nil {
		return fields
	}

	for _, f := range structType.Fields.List {
		fType, kind := analyzeType(f.Type)

		for _, name := range f.Names {
			fields = append(fields, field{
				name:  name.Name,
				fType: fType,
				kind:  kind,
			})
		}
	}

	return fields
}

func analyzeType(expr ast.Expr) (string, kind) {
	switch t := expr.(type) {
	case *ast.Ident:
		if isBuiltinPrimitive(t.Name) {
			return t.Name, kindPrimitive
		}
		return t.Name, kindStruct
	case *ast.ArrayType:
		return "", kindSlice
	case *ast.MapType:
		return "", kindMap
	case *ast.StarExpr:
		elemType, elemKind := analyzeType(t.X)
		if elemKind == kindPrimitive {
			return elemType, kindPointerPrimitive
		}
		return elemType, kindPointerStruct
	case *ast.SelectorExpr:
		if xIdent, ok := t.X.(*ast.Ident); ok {
			return xIdent.Name + "." + t.Sel.Name, kindStruct
		}
		return t.Sel.Name, kindStruct
	default:
		return "", kindPrimitive
	}
}

func isBuiltinPrimitive(typeName string) bool {
	switch typeName {
	case "string", "bool",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128", "byte", "rune":
		return true
	default:
		return false
	}
}

func generateResetFile(dirPath, pkgName string, structs []structData) error {
	var builder strings.Builder

	builder.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\npackage ")
	builder.WriteString(pkgName)
	builder.WriteString("\n\n")

	for _, st := range structs {
		builder.WriteString("func (rs *")
		builder.WriteString(st.name)
		builder.WriteString(") Reset() {\n\tif rs == nil {\n\t\treturn\n\t}\n")

		for _, f := range st.fields {
			switch f.kind {
			case kindPrimitive:
				genPrimitiveReset(&builder, f)

			case kindSlice:
				builder.WriteString("\trs.")
				builder.WriteString(f.name)
				builder.WriteString(" = rs.")
				builder.WriteString(f.name)
				builder.WriteString("[:0]\n")

			case kindMap:
				builder.WriteString("\tclear(rs.")
				builder.WriteString(f.name)
				builder.WriteString(")\n")

			case kindPointerPrimitive:
				builder.WriteString("\tif rs.")
				builder.WriteString(f.name)
				builder.WriteString(" != nil {\n\t\t*rs.")
				builder.WriteString(f.name)
				builder.WriteString(" = ")
				builder.WriteString(getZeroValue(f.fType))
				builder.WriteString("\n\t}\n")

			case kindPointerStruct:
				builder.WriteString("\tif resetter, ok := any(rs.")
				builder.WriteString(f.name)
				builder.WriteString(").(interface{ Reset() }); ok && rs.")
				builder.WriteString(f.name)
				builder.WriteString(" != nil {\n\t\tresetter.Reset()\n\t}\n")

			case kindStruct:
				builder.WriteString("\tif resetter, ok := any(&rs.")
				builder.WriteString(f.name)
				builder.WriteString(").(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t} else {\n\t\tvar zero ")
				builder.WriteString(f.fType)
				builder.WriteString("\n\t\trs.")
				builder.WriteString(f.name)
				builder.WriteString(" = zero\n\t}\n")

			}
		}

		builder.WriteString("}\n\n")
	}

	formatted, err := format.Source([]byte(builder.String()))
	if err != nil {
		return fmt.Errorf("Formatting failed: %w", err)
	}

	targetPath := filepath.Join(dirPath, "reset.gen.go")
	return os.WriteFile(targetPath, formatted, 0644)
}

func getZeroValue(primitiveType string) string {
	switch primitiveType {
	case "string":
		return `""`
	case "bool":
		return "false"
	default:
		return "0"
	}
}

func genPrimitiveReset(builder *strings.Builder, f field) {
	switch f.fType {
	case "string":
		builder.WriteString("\trs.")
		builder.WriteString(f.name)
		builder.WriteString(" = \"\"\n")

	case "bool":
		builder.WriteString("\trs.")
		builder.WriteString(f.name)
		builder.WriteString(" = false\n")

	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128", "byte", "rune":
		builder.WriteString("\trs.")
		builder.WriteString(f.name)
		builder.WriteString(" = 0\n")

	default:
		builder.WriteString("\tif v, ok := any(&rs.")
		builder.WriteString(f.name)
		builder.WriteString(").(interface{ Reset() }); ok {\n\t\tv.Reset()\n\t} else {\n\t\tvar zero ")
		builder.WriteString(f.fType)
		builder.WriteString("\n\t\trs.")
		builder.WriteString(f.name)
		builder.WriteString(" = zero\n\t}\n")
	}
}
