// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apomazanov/shortener/internal/handlers (interfaces: URLConfig)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_config.gen.go -package=mocks github.com/apomazanov/shortener/internal/handlers URLConfig
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockURLConfig is a mock of URLConfig interface.
type MockURLConfig struct {
	ctrl     *gomock.Controller
	recorder *MockURLConfigMockRecorder
	isgomock struct{}
}

// MockURLConfigMockRecorder is the mock recorder for MockURLConfig.
type MockURLConfigMockRecorder struct {
	mock *MockURLConfig
}

// NewMockURLConfig creates a new mock instance.
func NewMockURLConfig(ctrl *gomock.Controller) *MockURLConfig {
	mock := &MockURLConfig{ctrl: ctrl}
	mock.recorder = &MockURLConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLConfig) EXPECT() *MockURLConfigMockRecorder {
	return m.recorder
}

// GetURLBase mocks base method.
func (m *MockURLConfig) GetURLBase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLBase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetURLBase indicates an expected call of GetURLBase.
func (mr *MockURLConfigMockRecorder) GetURLBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLBase", reflect.TypeOf((*MockURLConfig)(nil).GetURLBase))
}
