// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apomazanov/shortener/internal/handlers (interfaces: BusinessService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_business.go -package=mocks github.com/apomazanov/shortener/internal/handlers BusinessService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBusinessService is a mock of BusinessService interface.
type MockBusinessService struct {
	ctrl     *gomock.Controller
	recorder *MockBusinessServiceMockRecorder
	isgomock struct{}
}

// MockBusinessServiceMockRecorder is the mock recorder for MockBusinessService.
type MockBusinessServiceMockRecorder struct {
	mock *MockBusinessService
}

// NewMockBusinessService creates a new mock instance.
func NewMockBusinessService(ctrl *gomock.Controller) *MockBusinessService {
	mock := &MockBusinessService{ctrl: ctrl}
	mock.recorder = &MockBusinessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusinessService) EXPECT() *MockBusinessServiceMockRecorder {
	return m.recorder
}

// CreateURLAlias mocks base method.
func (m *MockBusinessService) CreateURLAlias(ctx context.Context, original, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURLAlias", ctx, original, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateURLAlias indicates an expected call of CreateURLAlias.
func (mr *MockBusinessServiceMockRecorder) CreateURLAlias(ctx, original, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURLAlias", reflect.TypeOf((*MockBusinessService)(nil).CreateURLAlias), ctx, original, userID)
}

// CreateURLAliasBatch mocks base method.
func (m *MockBusinessService) CreateURLAliasBatch(ctx context.Context, originals []string, userID string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateURLAliasBatch", ctx, originals, userID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateURLAliasBatch indicates an expected call of CreateURLAliasBatch.
func (mr *MockBusinessServiceMockRecorder) CreateURLAliasBatch(ctx, originals, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateURLAliasBatch", reflect.TypeOf((*MockBusinessService)(nil).CreateURLAliasBatch), ctx, originals, userID)
}

// GetOriginalURL mocks base method.
func (m *MockBusinessService) GetOriginalURL(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockBusinessServiceMockRecorder) GetOriginalURL(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockBusinessService)(nil).GetOriginalURL), ctx, alias)
}

// GetUserURLs mocks base method.
func (m *MockBusinessService) GetUserURLs(ctx context.Context, userID string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userID)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockBusinessServiceMockRecorder) GetUserURLs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockBusinessService)(nil).GetUserURLs), ctx, userID)
}
